CD: modify the backend deployment url

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -19,14 +19,19 @@ jobs:
           PAYLOAD=$(jq -n --arg q "$QUERY" '{"query": $q}')
 
           RESPONSE_CODE=$(curl -s -X POST \
-            --url "https://backboard.railway.app" \
+            --url "https://backboard.railway.app/graphql/v2" \
             --header "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
             --header "Content-Type: application/json" \
             --data "$PAYLOAD" \
             -o response.json -w "%{http_code}")
 
           echo "Railway Response Code: $RESPONSE_CODE"
-          cat response.json
+           if [ "$RESPONSE_CODE" -eq 201 ] || [ "$RESPONSE_CODE" -eq 200 ]; then
+            echo "RailWay deployment triggered successfully!"
+          else
+            echo "Error: RailWay API failed with constants $RESPONSE_CODE"
+            exit 1
+          fi
 
   deploy-frontend:
     runs-on: ubuntu-latest
